AllCops:
  Exclude:
    - 'ext/**/*'
    - 'test/fixtures/**/*'

# Offense count: 1
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 228

# Offense count: 283
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 300

# Offense count: 17
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 36

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: true

# Offense count: 2
Style/EachWithObject:
  Enabled: false

# Offense count: 24
# Configuration parameters: SupportedStyles.
Style/For:
  EnforcedStyle: for

# Offense count: 17
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 2
Style/RegexpLiteral:
  MaxSlashes: 0

# Offense count: 2
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: false