AllCops:
  Exclude:
    - 'ext/**/*'
    - 'test/fixtures/**/*'

# Offense count: 283
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 300

# Offense count: 17
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 36
